src/helpers/utf8.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/xmoto/xmoto/3)

Fixed header guard name collision in utf8.h

---

src/XMSession.cpp
src/XMSession.h
src/states/GameState.cpp
src/states/GameState.h
src/states/StateScene.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/xmoto/xmoto/6)

Safemode bug fixed

---

extra/xmoto.desktop

This is taken from
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=641822
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/xmoto/xmoto/19)

Add German translation for .desktop GenericName

---

xmoto.6

Use em-dashes and minus symbols where appropriate.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/xmoto/xmoto/18)

Fix hyphens and spelling in the manpage

---

README.md

Sorry about that!
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/xmoto/xmoto/26)

Fixed active developer list

---

extra/xmoto.desktop

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/xmoto/xmoto/34)

Add Russian translation for .desktop GenericName

---

README.md
src/common/XMBuild_info.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/xmoto/xmoto/38)

Update copyright year

---

src/xmoto/LevelsManager.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/xmoto/xmoto/39)

Optimise slow query

---

src/db/xmDatabase.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/xmoto/xmoto/40)

Fix bug with sqlite call in user_xm_profile

---

extra/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/xmoto/xmoto/29)

desktop files are shared, put it in /usr/share

---

src/states/GameState.cpp
src/xmoto/SysMessage.cpp
src/xmoto/SysMessage.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/xmoto/xmoto/42)

Show the chat console when the chatbox is opened

---

src/CMakeLists.txt
src/helpers/Environment.cpp
vendor/xdgbasedir/CMakeLists.txt
vendor/xdgbasedir/src/basedir.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/xmoto/xmoto/43)

Add fixes for msys2

---

CMakeLists.txt
cpack/debian.cmake
src/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/xmoto/xmoto/52)

Fix rpm fs issue

---

src/xmoto/Renderer.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/xmoto/xmoto/54)

Colour checkpoints green in ugly mode to match minimap

---

bin/Levels/l1343.lvl
bin/Levels/l7978.lvl
bin/Levels/l8023.lvl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/xmoto/xmoto/59)

Make level compatible with latest version of lua

---

bin/CMakeLists.txt
cpack/win32.cmake
extra/xmoto.rc
src/CMakeLists.txt
tools/win32_copy_dlls.sh
tools/win32_strip_dlls.sh
vendor/xdgbasedir/src/basedir.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/xmoto/xmoto/61)

Prep for release

---

src/CMakeLists.txt

see https://gitlab.kitware.com/cmake/cmake/-/issues/16404

set lua differently, see kitware issue

---

i18n/po/da_DK.po

Let's see how my spelling has improved in 10 years :)

Update danish translation

---

src/drawlib/DrawLib.cpp
src/states/StateScene.cpp

GFX: Unset texture after drawing

---

.travis.yml
src/CMakeLists.txt

CMake: Add missing Intl_INCLUDE_DIRS

---

i18n/po/sv_SE.po

i18n: Update swedish translation

---

src/drawlib/DrawLibOpenGL.cpp

Add SDL_DestroyWindow after delete GL context

Fix memory leak at exit

---

.github/workflows/build.yml
.github/workflows/sonar.yml
sonar-project.properties

Add SonarCloud Back

---

.github/workflows/release.yml
CMake/macos.cmake
CMakeLists.txt

CMake: Fix libpng version mismatch on macOS

---

dev-scripts/clean.sh
dev-scripts/compile.sh
dev-scripts/run.sh
nix/xmoto.nix
src/common/VFileIO.cpp

See commit messages for details. :)

Fixes local builds on NixOS. Improve error reporting for missing paths. Add more fallbacks for finding xmoto.bin. Add build/run/clean dev scripts.

---

src/gui/specific/GUIXMoto.cpp
src/helpers/Text.cpp
src/states/StateLevelInfoViewer.cpp
src/states/StateScene.cpp
src/xmoto/Game.cpp
src/xmoto/GameText.h

To clarify that this is a decimal fraction rather than a sexagesimal one.

Use dot to delimit fractions of a second in formatTime

---

i18n/po/et.po

.po file for Estonian (eesti, et) translation

Add Estonian translation file
