src/helpers/utf8.h

Cherry pick from @Nikekson's fix in `master`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/xmoto/xmoto/5)

Fixed header guard name collision in utf8.h

---

src/CMakeLists.txt

Thanks to @Nikekson for catching this. Replaced with duplication of the predicate and `$<NOT:...>`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/xmoto/xmoto/11)

Remove $<IF:...>s for CMake 3.7 compatability

---

extra/xmoto.desktop

The GNOME HIG state that a submenu should have at least three items
before being used.
This is taken from
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=478974
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/xmoto/xmoto/13)

Add .desktop ArcadeGame sub-menu

---

src/common/WWW.cpp

This patch allows building X-Moto with GCC 7.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/xmoto/xmoto/16)

Avoid comparing pointers with booleans

---

src/xmoto/GameEvents.cpp
src/xmoto/GameEvents.h

This fixes some cppcheck performance warnings for GameEvents.cpp and GameEvents.h saying "Function parameter such-and-such should be passed by const reference."
Sorry about the duplicate push requests but apparently cant change which branch of my fork I want to pull from in the pull #21
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/xmoto/xmoto/22)

Fix cppcheck warnings, pass some strings by const&

---

src/states/StateManager.cpp

Running X-Moto in Valgrind 3.14.0 produces the following warning (there were others, but this was the biggest leak of a single run of X-Moto in Valgrind that didn't have a bunch of `???` frames):
```
==4999== 188,221 (256 direct, 187,965 indirect) bytes in 1 blocks are definitely lost in loss record 1,672 of 1,673
==4999==    at 0x4C2E91F: operator new(unsigned long) (in /usr/lib64/valgrind/vgpreload_memcheck-amd64-linux.so)
==4999==    by 0x50F11B: StateManager::StateManager() (StateManager.cpp:102)
==4999==    by 0x4B876B: Singleton<StateManager>::instance() (Singleton.h:33)
==4999==    by 0x58E6DA: GameApp::run_load(int, char**) (GameInit.cpp:403)
==4999==    by 0x58CFF8: GameApp::run(int, char**) (GameInit.cpp:158)
==4999==    by 0x58CE1C: main (GameInit.cpp:117)
==4999==    
```
This …

Fix leaking the download replays thread in StateManager.

---

src/xmscene/BikeGhost.cpp

Like #32 this is another small change that fixes a leak. I didn't notice this leak at first because I didn't test out the replay functionality under Valgrind before.
The Replay `m_replay` was created (with `new`) in the constructor of `FileGhost` but was never deleted in the destructor; this causes the replay file not to be freed (the `Replay` destructor would have freed the file with `Replay::_FreeReplay`). Deleting the m_replay in FileGhost's destructor should free the file.
`Valgrind --fullpath-after=/mnt/d/Linux_home/nathan/src/xmoto-git/ --undef-value-errors=no --leak-check=full --show-leak-kinds=definite build/src/xmoto`
```
...
==472== 9,260 (304 direct, 8,956 indirect) bytes in 1 blocks are definitely lost in loss record 1,763 of 1,768
==472==    at 0x4C2E91F: operator …
```

Fix leaking the ghost replay file.

---

src/drawlib/DrawLibOpenGL.cpp
src/xmoto/Game.cpp
src/xmoto/Sound.cpp

This pull request fixes the following tiny leaks:
- an `RWops` structure (64 byte leak) in `Sound::loadSample` that leaked 18 times.
- the replay info (104 byte leak)
- the never deleted m_menuCamera (208 byte leak)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/xmoto/xmoto/35)

A few small leak fixes

---

src/drawlib/DrawLib.cpp
src/drawlib/DrawLib.h
src/xmscene/Camera.cpp

When the camera is deleted, its `m_renderSurf` is still referenced from DrawLib. Camera's `m_renderSurf` is invalid after it is deleted, so DrawLib's `m_renderSurf` is rendered invalid. To fix this, I added a boolean parameter to `setRenderSurface` which tells DrawLib whether it owns the pointer. This boolean is set when creating a new RenderSurface in the `setRenderSurface()` call, and not when passing a pointer to the `m_renderSurf` inside of Camera.
This seems to fix the "Invalid read of size 4" mentioned in issue #36.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/xmoto/xmoto/37)

Fix #36: Invalid read of size 4 after playing replay.

---

src/drawlib/DrawLib.cpp
src/drawlib/DrawLib.h
src/gui/basic/GUI.cpp
src/gui/basic/GUI.h

This isn't used by anything yet but it would be useful if we ever want to get around to refactoring drawlib, or add any non-square elements anywhere.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/xmoto/xmoto/41)

Add draw function for drawing polygons

---

src/image/tim_jpeg.cpp

Fixes a bug I ran across with MXE builds where jpeg textures were being scaled by 8x
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/xmoto/xmoto/45)

Use a default scale of 1/1 for jpeg

---

src/common/Image.cpp
src/image/tim.cpp
src/image/tim.h
src/image/tim_io_stdio.cpp
src/image/tim_jpeg.cpp
src/image/tim_png.cpp

This fixes all the warnings of the form "ISO C++ forbids converting a
string constant to ‘char*’" except in the vendored code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/xmoto/xmoto/58)

Fix constant string conversions

---

src/CMakeLists.txt
src/xmoto/LuaLibBase.h

This involves changing the include paths to drop the lua/ directory,
as indicated in FindLua5.1.cmake.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/xmoto/xmoto/60)

Allow building with the system Lua (5.1)

---

src/xmoto/XMKey.cpp

Fixes warnings and probably incorrectly working code as unsigned int cannot be compared to string::npos

Fix type for string index

---

src/include/xm_hashmap.h

There's no `std::tr1` with e.g. libc++. Let's switch this bit to proper C++11 finally.

Take unordered_map from std namespace

---

src/xmoto/GameEvents.cpp

The current implementation behaves incorrectly, effectively trimming start of message string by a number of characters equal to player number. Explicitly stringify player number to fix the behavior.

Fix formatting messages with player number

---

src/CMakeLists.txt

instead of insisting on lua-5.1, do not care. set the
corresponding compatibility option.
see https://gitlab.kitware.com/cmake/cmake/-/issues/18067.

not care which lua, set compatibility option

---

src/states/StateMainMenu.cpp

This was taken from
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=492414
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/xmoto/xmoto/15)

Avoid segfaulting on null database entries

---

src/drawlib/DrawLib.cpp
src/xmscene/Camera.cpp

m_renderSurf was uninitialized when the first call to DrawLib::setRenderSurface
was made. This caused Valgrind to complain "Conditional jump or move depends on uninitialised value(s)" and 'monitor get_vbits <address of m_renderSurf> 8' in gdb to output ffffffff ffffffff
To fix this simply add m_renderSurf = NULL in the DrawLib constructor.
==868== Conditional jump or move depends on uninitialised value(s)
==868==    at 0x47669B: DrawLib::setRenderSurface(RenderSurface*, bool) (DrawLib.cpp:413)
==868==    by 0x61975D: Camera::activate() (Camera.cpp:661)
==868==    by 0x61987F: Camera::setCamera2d() (Camera.cpp:677)
==868==    by 0x478377: DrawLibOpenGL::init(unsigned int, unsigned int, unsigned int, bool) (DrawLibOpenGL.cpp:346)
==868==    by 0x58EA0A: GameApp::run_load(int, char**) …

Fix conditional jump or move errors from Valgrind

---

src/states/StateOptions.cpp
src/states/StateOptions.h

`createRoomsList` was allocating strings for the room IDs and storing them in `pvUser`. These strings only got freed on a subsequent call to `createRoomsList` and then replaced with new strings. There wasn't a cleanup method for the room lists so I copy-pasted parts of the existing `updateRoomsList` and `createRoomsList` methods to create cleanup methods. This could probably be done with less duplication but `StateOptions::clean` is a static method, so it can't call non-static methods.
I tried changing `updateRoomsList` to take a boolean `clear` that would make it clear the room list instead of updating it and calling that from StateOptions::clean but it wouldn't compile since static methods can't call non-static methods.
```
==3673== 192 bytes in 6 blocks are definitely lost in loss …
```

Fix 192 byte leak in createRoomsList

---

src/db/xmDatabase_sync.cpp

v_result wasn't getting freed after every call to `readDB`, so I added some `read_DB_free()` calls to fix the leaks.
Valgrind errors (with `valgrind --leak-check=full --show-leak-kinds=definite build/src/xmoto`):
```
==6643== 12,352 (3,344 direct, 9,008 indirect) bytes in 1 blocks are definitely lost in loss record 1,540 of 1,546
==6643==    at 0x4C308BF: realloc (in /usr/lib64/valgrind/vgpreload_memcheck-amd64-linux.so)
==6643==    by 0x706A0E8: ??? (in /usr/lib64/libsqlite3.so.0.8.6)
==6643==    by 0x704159B: ??? (in /usr/lib64/libsqlite3.so.0.8.6)
==6643==    by 0x70DBE3F: sqlite3_get_table (in /usr/lib64/libsqlite3.so.0.8.6)
==6643==    by 0x459531: xmDatabase::readDB(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int&) …
```

Fix two memory leaks in xmDatabase::sync_buildServerFile

---

src/helpers/TFunctor.h

The wrong destructor was called when deleting TFunctor since it didn't
have a virtual destructor. This caused a string to leak. Since the
TFunctor1ARef destructor wasn't called, `m_argument1` (a string in the
case of `XMSession::setClientServerName`) wasn't destructed.
The leak report from Valgrind:
```
==18963== 31 bytes in 1 blocks are definitely lost in loss record 247 of 1,534
==18963==    at 0x4C2E94F: operator new(unsigned long) (in /usr/lib64/valgrind/vgpreload_memcheck-amd64-linux.so)
==18963==    by 0x7AAE31E: std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (in /usr/lib64/libstdc++.so.6.0.25)
==18963==    by 0x7AAE648: std::__cxx11::basic_string<char, …
```

Fix tiny memory leak in TFunctor1ARef.

---

src/xmoto/Game.cpp
src/xmoto/Game.h

The window icon was loaded in GameApp::_initWin but never freed. The documentation on [SDL_LoadBMP](https://wiki.libsdl.org/SDL_LoadBMP) says the new surface should be freed with `SDL_FreeSurface`. I added a call to SDL_FreeSurface in the GameApp destructor to free the new `m_icon` variable that is set to the window icon `v_icon` in _initWin. `m_icon` is initialized to NULL in GameApp constructor.
Valgrind error:
```
==20034== 4,324 (88 direct, 4,236 indirect) bytes in 1 blocks are definitely lost in loss record 1,519 of 1,531
==20034==    at 0x4C2E2DF: malloc (in /usr/lib64/valgrind/vgpreload_memcheck-amd64-linux.so)
==20034==    by 0x676BD2B: SDL_CreateRGBSurface (in /usr/lib64/libSDL-1.2.so.0.11.4)
==20034==    by 0x6766EDE: SDL_LoadBMP_RW (in /usr/lib64/libSDL-1.2.so.0.11.4)
==20034== …
```

Fix window icon memory leak.

---

src/drawlib/DrawLibOpenGL.cpp

This fixes a small memory leak in `DrawLibOpenGL::init`  by freeing the icon surface immediately after attaching it to the window like the code example at [SDL Wiki](https://wiki.libsdl.org/SDL_SetWindowIcon) shows.
Valgrind leak report:
```
==13022== 3,672 (96 direct, 3,576 indirect) bytes in 1 blocks are definitely lost in loss record 4,743 of 4,847
==13022==    at 0x4C306B5: calloc (in /usr/lib64/valgrind/vgpreload_memcheck-amd64-linux.so)
==13022==    by 0x657EE90: SDL_calloc_REAL (in /usr/lib64/libSDL2-2.0.so.0.10.0)
==13022==    by 0x65B54D0: SDL_CreateRGBSurfaceWithFormat_REAL (in /usr/lib64/libSDL2-2.0.so.0.10.0)
==13022==    by 0x65AD8C0: SDL_LoadBMP_RW_REAL (in /usr/lib64/libSDL2-2.0.so.0.10.0)
==13022==    by 0x478C7F: DrawLibOpenGL::init(unsigned int, unsigned int, unsigned …
```

SDL2: Fix window icon leak.

---

.gitignore
default.nix
nix/default.nix
nix/xmoto.nix
src/CMakeLists.txt

nix build -L --show-trace \
'((import ./. { enableCmakeNinja = true; }).xmoto)'
This makes it way easier for me (on NixOS) to test out our build system.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/xmoto/xmoto/105)

Nix: In-tree Nixpkgs derivation

---

src/helpers/System.cpp
src/xmoto/Replay.cpp
src/xmoto/Sound.cpp

In System.cpp, when `SDL_ListModes` fails, an exception is thrown without deleting `modes` first. In Replay.cpp, when the magic number check fails, `pRpl` isn't deleted. In Sound.cpp, when opening a file fails, `pSample` is leaked because an exception is thrown and the sample isn't deleted before the pointer to it goes away.
Here's the errors from Cppcheck:
```
[src\helpers\System.cpp:49]: (error) Memory leak: modes
[src\xmoto\Replay.cpp:1027]: (error) Memory leak: pRpl
[src\xmoto\Sound.cpp:175]: (error) Memory leak: pSample
```

Fix a few memory leaks found by Cppcheck.

---

src/CMakeLists.txt
src/helpers/ScopedTimer.h

Usage is as follows:
```cpp
{
ScopedTimer<std::chrono::milliseconds> t; // timer gets created and started
std::this_thread::sleep_for(std::chrono::milliseconds(100));
} // when it goes out of scope, it calculates the elapsed time and prints it
```

Add a scoped timer class

---

src/CMakeLists.txt

This is likely incomplete (you generally need corresponding include directory for each target_link_libraries entry), but works for me

Add missing curl include directories

---

src/CMakeLists.txt

Since ODE 0.16, physics in certain levels are unreliable, the primary issue being that the wheels can go through walls.
The breaking commit is https://bitbucket.org/odedevs/ode/commits/cd3539c929b2e29b011c87a94eab5bffeb018921

Drop support for system ODE

---

src/db/xmDatabase.cpp
src/helpers/Time.cpp
src/helpers/Time.h
src/xmoto/GameInit.cpp

Windows doesn't like `:`s in file names, which caused the game to crash on startup when a database backup is done

Hotfix for 0.6.2

---

src/common/VFileIO.cpp

Needed for AppImages to work, without having to make everything relocatable

Allow data directory to be loaded from $APPDIR

---

CMakeLists.txt
src/CMakeLists.txt
src/common/BuildConfig.h
src/common/DBuffer.cpp
src/common/VCommon.h
src/helpers/SwapEndian.cpp
src/helpers/SwapEndian.h
src/xmoto/GameInit.cpp

Allows target system's endianness to be determined automatically, the same way it was done with Autotools
Fixes #173

CMake: Set endianness flag during configuration

---

src/CMakeLists.txt

Mark system include directories with SYSTEM to avoid picking system includes instead of vendored ones and vice versa

Fix include directories

---

src/db/xmDatabase.cpp

SQLite can allow double-quoted strings as an extension/quirk, but this can be disabled. Since X-Moto always uses double-quoted strings, configure the database to always allow this.
This will do nothing if DQS is already enabled, or if the current version of SQLite doesn't know about the DQS knob, so it should always be safe.
See https://www.sqlite.org/quirks.html#double_quoted_string_literals_are_accepted for the description of this configuration parameter.
See https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=278669 for a description of a system where this causes xmoto to crash

xmDatabase: Always allow double-quoted strings

---

src/xmscene/Entity.cpp
src/xmscene/Entity.h
src/xmscene/Level.cpp

Entity::createEntity is returning a new Joint, Checkpoint, or Entity which is being leaked by one of the enclosing functions. Level::importBinary (Level.cpp:1182) is adding the returned Entity as a Joint to m_joints. Later, in Level::unloadToPlay calls unloadToPlay on each Joint in m_joints. Level::unloadToPlay is called by ~Level, Scene::endLevel, and Level::unloadLevelBody.
Need to free Chipmunk joint when deleting instances of Joint class. Added code to Joint::unloadToPlay to remove the joint from the chipmunk space and then free it, since the corresponding loadToPlay creates a joint and adds it to a space.
Note: this probably doesn't apply if the chipmunk 7 PR gets merged first,.
Leaks found with Valgrind running in openSUSE on Windows Subsystem for Linux version 1 on Windows 10
XMoto …

Fix minor 4KiB createEntity and cpPinJointNew memory leak

---

nix/xmoto.nix
src/CMakeLists.txt
src/common/VFileIO.cpp

This fixes compile on NixOS using `nix-build`. The `xmoto.nix` file was pulling in SDL1 instead of SDL2, which caused errors about SDL.h missing when compiling. Also, glu.h was "missing", but only because xmoto.nix didn't declare that the game uses libGLU. The second commit correctly finds the location of the missing _xmoto.bin_ file which is in the _share/xmoto_ folder next to the _bin_ once it is installed into _/nix/store_.

Fixes for NixOS

---

i18n/gettextize

building on arch linux gives:
--sort-output is an obsolete options.
see:
https://aur.archlinux.org/packages/xmoto

msgmerge --sourt-output is obsolete option
